### PR TITLE
Angular/lazy module

### PR DESCRIPTION
**Pull request by IKatsuba**
# Lazy Loaded Angular Modules

Now microzord core has functions to register, load and save any entities.
```ts
resisterEntity({
  name: 'someName',
  load: () => import('some/entity').then(m => m.Entity)
})
```

All app functions are based on entity functions.

This opportunity lets us lazy load Angular modules.

### Register a module in the host app

Use `MicrozordHostModule.register` for module registration

```ts
import {NgModule} from '@angular/core';

import {AppComponent} from './app.component';
import {MicrozordHostModule} from '@microzord/angular';

@NgModule({
  declarations: [AppComponent],
  imports: [
    ...,
    MicrozordHostModule.register({
      modules: [
        {
          name: 'remote',
          load: () => import('remote/App').then(m => m.App),
        },
        {
          name: 'demo',
          load: () => import('demo/App').then(m => m.App),
        },
      ],
    }),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

### Implement the `MicrozordNgModule` in a child app

```ts
import {NgModule, Type} from '@angular/core';

import {AppComponent} from './app.component';
import {MicrozordNgModule} from '@microzord/angular';

@NgModule({
  declarations: [AppComponent],
})
export class AppModule implements MicrozordNgModule<AppComponent> {
  getEntryPoint(): Type<AppComponent> {
    return AppComponent;
  }
}

```
### Use directive in template

```html
<ng-container microzordNgModule="demo"></ng-container>
```

And that's all!

### CODE REVIEW

**Comment by zy2ba** [comment]
Hmm... At this PR in "remote" example in "app" shows how to implements NgModule variant, but example of how to connect something in "app mode" now gone? I'm correct? If true, it's looks totally discourageble.
May be need save both - NgModule and App examples? 
Also as "app mode" may be uses some React or Vue for more representation? Because for Angular NgModule became better opportunity and best usage for "app mode" is React and etc.

**Comment by IKatsuba** [comment]
@zy2ba, you are right. I remove the `app` example, but it is not an example. And I don't want to do any examples before the first stable version of Microzord.

**Comment by IKatsuba** [comment]
:tada: This pull request is included in version core@1.0.0-alpha.2 :tada:

The release is available on [GitHub release](<github_release_url>)

**Comment by IKatsuba** [comment]
:tada: This pull request is included in version angular@1.0.0-alpha.2 :tada:

The release is available on [GitHub release](<github_release_url>)

**Pull request merged**
